<?php
/**
 * Language labels for database tables/fields belonging to extension "static_info_tables"
 * 
 * This file is detected by the translation tool.
 */


$LOCAL_LANG = Array (
	'default' => Array (
		'static_countries.title' =>'Countries',
		'static_countries_item.cn_iso_2' => 'ISO 2 country code:',
		'static_countries_item.cn_iso_3' => 'ISO 3 country code:',
		'static_countries_item.cn_iso_nr' => 'ISO nr country code:',
		'static_countries_item.cn_official_name_local' => 'Official name (local):',
		'static_countries_item.cn_official_name_en' => 'Official name (EN):',
		'static_countries_item.cn_capital' => 'Capital:',
		'static_countries_item.cn_tldomain' => 'Top level domain:',
		'static_countries_item.cn_currency_iso_nr' => 'ISO nr currency code:',
		'static_countries_item.cn_currency_iso_3' => 'ISO 3 currency code:',
		'static_countries_item.cn_phone' => 'Int. phone prefix:',
		'static_countries_item.cn_eu_member' => 'EU member:',
		'static_countries_item.cn_address_format' => 'Address format:',
		'static_countries_item.cn_address_format_1' => 'zip city',
		'static_countries_item.cn_address_format_2' => 'city zip',
		'static_countries_item.cn_address_format_3' => 'city region-code zip',
		'static_countries_item.cn_address_format_4' => 'city (region-name) zip',
		'static_countries_item.cn_address_format_5' => 'city/zip',
		'static_countries_item.cn_address_format_6' => 'zip city, region-code',
		'static_countries_item.cn_address_format_7' => 'zip city region-code',
		'static_countries_item.cn_address_format_8' => 'zip city (region-name)',
		'static_countries_item.cn_zone_flag' => 'Zone flag:',
		'static_countries_item.cn_short_local' => 'Short name (local):',
		'static_countries_item.cn_short_en' => 'Short name (EN):',
		'static_countries_item.cn_short_dk' => 'Short name (DK):',
		'static_countries_item.cn_short_de' => 'Short name (DE):',

		'static_country_zones.title' =>'Country subdivisions',
		'static_country_zones_item.zn_country_iso_nr' => 'ISO nr country code:',
		'static_country_zones_item.zn_country_iso_2' => 'ISO 2 country code:',
		'static_country_zones_item.zn_country_iso_3' => 'ISO 3 country code:',
		'static_country_zones_item.zn_code' => 'Zone code:',

		'static_languages.title' =>'Languages',
		'static_languages_item.lg_iso_2' => 'ISO 2 language code:',
		'static_languages_item.lg_name_en' => 'Name (EN):',
		'static_languages_item.lg_name_fr' => 'Name (FR):',
		'static_languages_item.lg_name_de' => 'Name (DE):',
		'static_languages_item.lg_name_es' => 'Name (ES):',
		'static_languages_item.lg_name_nl' => 'Name (NL):',
		'static_languages_item.lg_typo3' => 'Typo3 language code:',

		'static_currencies.title' =>'Currencies',
		'static_currencies_item.cu_iso_3' => 'ISO 3 currency code:',
		'static_currencies_item.cu_iso_nr' => 'ISO nr currency code:',
		'static_currencies_item.cu_name_en' => 'Name (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Sub name (EN):',
		'static_currencies_item.cu_name_de' => 'Name (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Sub name (DE):',
		'static_currencies_item.cu_symbol_left' => 'Symbol left:',
		'static_currencies_item.cu_symbol_right' => 'Symbol right:',
		'static_currencies_item.cu_thousands_point' => 'Thousands point:',
		'static_currencies_item.cu_decimal_point' => 'Decimal point:',
		'static_currencies_item.cu_decimal_digits' => 'Decimal digits:',
		'static_currencies_item.cu_sub_divisor' => 'Divisor:',
		'static_currencies_item.cu_sub_symbol_left' => 'Sub symbol left:',
		'static_currencies_item.cu_sub_symbol_right' => 'Sub symbol right:',	
	),
	'dk' => Array (
	),
	'de' => Array (
		'static_countries.title' =>'Länder',
		'static_countries_item.cn_iso_2' => 'ISO 2 Ländercode:',
		'static_countries_item.cn_iso_3' => 'ISO 3 Ländercode:',
		'static_countries_item.cn_iso_nr' => 'ISO Nr Ländercode:',
		'static_countries_item.cn_official_name_local' => 'Offizieller Name (lokal):',
		'static_countries_item.cn_official_name_en' => 'Offizieller Name (EN):',
		'static_countries_item.cn_capital' => 'Hauptstadt:',
		'static_countries_item.cn_tldomain' => 'Toplevel Domain:',
		'static_countries_item.cn_currency_iso_nr' => 'ISO Nr Währungscode:',
		'static_countries_item.cn_currency_iso_3' => 'ISO 3 Währungscode:',
		'static_countries_item.cn_phone' => 'Tel. Vorwahl:',
		'static_countries_item.cn_eu_member' => 'EU-Mitglied:',
		'static_countries_item.cn_address_format' => 'Adressformat:',
		'static_countries_item.cn_address_format_1' => 'PLZ Ort',
		'static_countries_item.cn_address_format_2' => 'Ort PLZ',
		'static_countries_item.cn_address_format_3' => 'Ort Regionskürzel PLZ',
		'static_countries_item.cn_address_format_4' => 'Stadt (Region) PLZ',
		'static_countries_item.cn_address_format_5' => 'Stadt/PLZ',
		'static_countries_item.cn_address_format_6' => 'PLZ Ort, Regionskürzel',
		'static_countries_item.cn_address_format_7' => 'PLZ Ort (Regionskürzel)',
		'static_countries_item.cn_address_format_8' => 'PLZ Stadt (Region)',
		'static_countries_item.cn_zone_flag' => 'Zone flag:',
		'static_countries_item.cn_short_local' => 'Kurzname (lokal):',
		'static_countries_item.cn_short_en' => 'Kurzname (EN):',
		'static_countries_item.cn_short_dk' => 'Kurzname (DK):',
		'static_countries_item.cn_short_de' => 'Kurzname (DE):',
		'static_country_zones.title' =>'Landesteile (Bundesländer)',
		'static_country_zones_item.zn_country_iso_nr' => 'ISO Nr Ländercode:',
		'static_country_zones_item.zn_country_iso_2' => 'ISO 2 Ländercode:',
		'static_country_zones_item.zn_country_iso_3' => 'ISO 3 Ländercode:',
		'static_country_zones_item.zn_code' => 'Code:',
		'static_languages.title' =>'Sprachen',
		'static_languages_item.lg_iso_2' => 'ISO 2 Sprachcode:',
		'static_languages_item.lg_name_en' => 'Name (EN):',
		'static_languages_item.lg_name_fr' => 'Name (FR):',
		'static_languages_item.lg_name_de' => 'Name (DE):',
		'static_languages_item.lg_name_es' => 'Name (ES):',
		'static_languages_item.lg_name_nl' => 'Name (NL):',
		'static_languages_item.lg_typo3' => 'Typo3 Sprachcode:',
		'static_currencies.title' =>'Währungen',
		'static_currencies_item.cu_iso_3' => 'ISO 3 Währungscode:',
		'static_currencies_item.cu_iso_nr' => 'ISO Nr Währungscode:',
		'static_currencies_item.cu_name_en' => 'Name (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Sub-Name (EN):',
		'static_currencies_item.cu_name_de' => 'Name (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Sub-Name (DE):',
		'static_currencies_item.cu_symbol_left' => 'Symbol links:',
		'static_currencies_item.cu_symbol_right' => 'Symbol rechts:',
		'static_currencies_item.cu_thousands_point' => 'Tausender Punkt:',
		'static_currencies_item.cu_decimal_point' => 'Dezimal Punkt:',
		'static_currencies_item.cu_decimal_digits' => 'Dezimalstellen:',
		'static_currencies_item.cu_sub_divisor' => 'Divisor:',
		'static_currencies_item.cu_sub_symbol_left' => 'Sub-Symbol links:',
		'static_currencies_item.cu_sub_symbol_right' => 'Sub-Symbol rechts:',
	),
	'no' => Array (
	),
	'it' => Array (
		'static_countries_item.cn_iso_2' => 'Codice nazione ISO 2:',
		'static_countries_item.cn_iso_3' => 'Codice nazione ISO 3:',
		'static_countries_item.cn_iso_nr' => 'Numero codice nazione ISO:',
		'static_countries_item.cn_official_name_local' => 'Nome ufficiale (locale):',
		'static_countries_item.cn_official_name_en' => 'Nome ufficiale (EN):',
		'static_countries_item.cn_capital' => 'Capitale:',
		'static_countries_item.cn_tldomain' => 'Dominio di primo livello:',
		'static_countries_item.cn_currency_iso_nr' => 'Numero codice valuta ISO:',
		'static_countries_item.cn_currency_iso_3' => 'Codice valuta ISO 3:',
		'static_countries_item.cn_phone' => 'Prefisso internazionale:',
		'static_countries_item.cn_eu_member' => 'Membro UE:',
		'static_countries_item.cn_address_format' => 'Formato indirizzo:',
		'static_countries_item.cn_address_format_1' => 'CAP città',
		'static_countries_item.cn_address_format_2' => 'città cap',
		'static_countries_item.cn_address_format_3' => 'città regione cap',
		'static_countries_item.cn_zone_flag' => 'Zone flag:',
		'static_countries_item.cn_short_local' => 'Nome breve (locale):',
		'static_countries_item.cn_short_en' => 'Nome breve (EN):',
		'static_countries_item.cn_short_dk' => 'Nome breve (DK):',
		'static_countries_item.cn_short_de' => 'Nome breve (DE):',
		'static_country_zones_item.zn_country_iso_nr' => 'Numero codice nazione ISO:',
		'static_country_zones_item.zn_country_iso_2' => 'Codice nazione ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Codice nazione ISO 3:',
		'static_country_zones_item.zn_code' => 'Codice zona:',
		'static_languages_item.lg_iso_2' => 'Codice lingua ISO 2:',
		'static_languages_item.lg_name_en' => 'Nome (EN):',
		'static_currencies_item.cu_iso_3' => 'Codice valuta ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Numero codice valuta ISO:',
		'static_currencies_item.cu_name_en' => 'Nome (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Nome decimali (EN):',
		'static_currencies_item.cu_name_de' => 'Nome (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Nome decimali (DE):',
		'static_currencies_item.cu_symbol_left' => 'Simbolo a sinistra:',
		'static_currencies_item.cu_symbol_right' => 'Simbolo a destra:',
		'static_currencies_item.cu_thousands_point' => 'Simbolo raggruppamento cifre:',
		'static_currencies_item.cu_decimal_point' => 'Separatore decimale:',
		'static_currencies_item.cu_decimal_digits' => 'Cifre decimali:',
		'static_currencies_item.cu_sub_divisor' => 'Rapporto decimali/unità:',
		'static_currencies_item.cu_sub_symbol_left' => 'Simbolo decimali a sinistra:',
		'static_currencies_item.cu_sub_symbol_right' => 'Simbolo decimali a destra:',
	),
	'fr' => Array (
		'static_countries.title' => 'Pays - Données statiques',
		'static_countries_item.cn_iso_2' => 'Code de pays ISO 2:',
		'static_countries_item.cn_iso_3' => 'Code de pays ISO 3:',
		'static_countries_item.cn_iso_nr' => 'Code de pays ISO numérique:',
		'static_countries_item.cn_official_name_local' => 'Nom officiel (local):',
		'static_countries_item.cn_official_name_en' => 'Nom officiel (EN):',
		'static_countries_item.cn_capital' => 'Capitale:',
		'static_countries_item.cn_tldomain' => 'Domaine de premier niveau:',
		'static_countries_item.cn_currency_iso_nr' => 'Code de devise ISO numérique:',
		'static_countries_item.cn_currency_iso_3' => 'Code de devise ISO 3:',
		'static_countries_item.cn_phone' => 'Préfixe téléphonique international:',
		'static_countries_item.cn_eu_member' => 'Membre de l\'Union européenne:',
		'static_countries_item.cn_address_format' => 'Format d\'adresse:',
		'static_countries_item.cn_address_format_1' => 'code-postal  localité',
		'static_countries_item.cn_address_format_2' => 'localité code-postal',
		'static_countries_item.cn_address_format_3' => 'localité code-de-région code-postal',
		'static_countries_item.cn_address_format_4' => 'localité (nom-de-région) code-postal',
		'static_countries_item.cn_address_format_5' => 'localité/code-postal',
		'static_countries_item.cn_address_format_6' => 'code-postal localité, code-de-région',
		'static_countries_item.cn_address_format_7' => 'code-postal localité code-de-région',
		'static_countries_item.cn_address_format_8' => 'code-postal localité (nom-de-région)',
		'static_countries_item.cn_zone_flag' => 'Indicateur de subdivision:',
		'static_countries_item.cn_short_local' => 'Nom court (local):',
		'static_countries_item.cn_short_en' => 'Nom court (EN):',
		'static_countries_item.cn_short_dk' => 'Nom court (DK):',
		'static_countries_item.cn_short_de' => 'Nom court (DE):',
		'static_country_zones.title' => 'Subdivision de pays - Données statiques',
		'static_country_zones_item.zn_country_iso_nr' => 'Code de pays ISO numérique:',
		'static_country_zones_item.zn_country_iso_2' => 'Code de pays ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Code de pays ISO 3:',
		'static_country_zones_item.zn_code' => 'Code de subdivision de pays:',
		'static_country_zones_item.zn_name_local' => 'Nom local de subdivision de pays:',
		'static_languages.title' => 'Langue - Données statiques',
		'static_languages_item.lg_iso_2' => 'Code de langue ISO 2:',
		'static_languages_item.lg_name_en' => 'Nom de langue (EN):',
		'static_languages_item.lg_typo3' => 'Code de langue Typo3:',
		'static_currencies.title' => 'Devise - Données statiques',
		'static_currencies_item.cu_iso_3' => 'Code de devise ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Code de devise ISO numérique:',
		'static_currencies_item.cu_name_en' => 'Nom (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Nom de subdivision (EN):',
		'static_currencies_item.cu_name_de' => 'Nom (DE):',
		'static_currencies_item.cu_name_fr' => 'Nom (FR):',
		'static_currencies_item.cu_name_es' => 'Nom (ES):',
		'static_currencies_item.cu_sub_name_de' => 'Nom de subdivision (DE):',
		'static_currencies_item.cu_sub_name_fr' => 'Nom de subdivision (FR):',
		'static_currencies_item.cu_sub_name_es' => 'Nom de subdivision (ES):',
		'static_currencies_item.cu_symbol_left' => 'Symbole à gauche:',
		'static_currencies_item.cu_symbol_right' => 'Symbole à droite:',
		'static_currencies_item.cu_thousands_point' => 'Marque des milliers:',
		'static_currencies_item.cu_decimal_point' => 'Marque décimale:',
		'static_currencies_item.cu_decimal_digits' => 'Nombre de décimales:',
		'static_currencies_item.cu_sub_divisor' => 'Diviseur:',
		'static_currencies_item.cu_sub_symbol_left' => 'Symbole à gauche - Subdivision:',
		'static_currencies_item.cu_sub_symbol_right' => 'Symbole à droite - Subdivision:',
	),
	'es' => Array (
		'static_countries.title' => 'País - Datos státicos',
		'static_countries_item.cn_iso_2' => 'Código de país ISO 2:',
		'static_countries_item.cn_iso_3' => 'Código de país ISO 3:',
		'static_countries_item.cn_iso_nr' => 'Código de país ISO numérico:',
		'static_countries_item.cn_official_name_local' => 'Nombre oficial (local):',
		'static_countries_item.cn_official_name_en' => 'Nombre oficial (EN):',
		'static_countries_item.cn_capital' => 'Capital:',
		'static_countries_item.cn_tldomain' => 'Dominio de primer nivel:',
		'static_countries_item.cn_currency_iso_nr' => 'Código de divisa ISO numérico:',
		'static_countries_item.cn_currency_iso_3' => 'Código de divisa ISO 3:',
		'static_countries_item.cn_phone' => 'Prefijo telefónico internacional:',
		'static_countries_item.cn_eu_member' => 'Miembro de la Union európea:',
		'static_countries_item.cn_address_format' => 'Formato de dirección:',
		'static_countries_item.cn_address_format_1' => 'código-postal  localidad',
		'static_countries_item.cn_address_format_2' => 'localidad  código-postal',
		'static_countries_item.cn_address_format_3' => 'localidad código-de-región  código-postal',
		'static_countries_item.cn_address_format_4' => 'localidad (nombre-de-región) código-postal',
		'static_countries_item.cn_address_format_5' => 'localidad/código-postal',
		'static_countries_item.cn_address_format_6' => 'código-postal localidad, código-de-región',
		'static_countries_item.cn_address_format_7' => 'código-postal localidad código-de-región',
		'static_countries_item.cn_address_format_8' => 'código-postal localidad (nombre-de-región)',
		'static_countries_item.cn_zone_flag' => 'Indicador de subdivisión:',
		'static_countries_item.cn_short_local' => 'Nombre corto (local):',
		'static_countries_item.cn_short_en' => 'Nombre corto (EN):',
		'static_countries_item.cn_short_dk' => 'Nombre corto (DK):',
		'static_countries_item.cn_short_de' => 'Nombre corto (DE):',
		'static_country_zones.title' => 'Subdivisión de país - Datos státicos',
		'static_country_zones_item.zn_country_iso_nr' => 'Código de país ISO numérico:',
		'static_country_zones_item.zn_country_iso_2' => 'Código de país ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Código de país ISO 3:',
		'static_country_zones_item.zn_code' => 'Código de subdivisión de país:',
		'static_country_zones_item.zn_name_local' => 'Nombre de subdivisión de país:',
		'static_languages.title' => 'Idioma - Datos státicos',
		'static_languages_item.lg_iso_2' => 'Código de idioma ISO 2:',
		'static_languages_item.lg_name_en' => 'Nombre de idioma (EN):',
		'static_languages_item.lg_typo3' => 'Código de idioma Typo3:',
		'static_currencies.title' => 'Divisa - Datos státicos',
		'static_currencies_item.cu_iso_3' => 'Código de divisa ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Código de divisa ISO numérico:',
		'static_currencies_item.cu_name_en' => 'Nombre (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Nombre de subdivisión (EN):',
		'static_currencies_item.cu_name_de' => 'Nombre (DE):',
		'static_currencies_item.cu_name_fr' => 'Nombre (FR):',
		'static_currencies_item.cu_name_es' => 'Nombre (ES):',
		'static_currencies_item.cu_sub_name_de' => 'Nombre de subdivisión (DE):',
		'static_currencies_item.cu_sub_name_fr' => 'Nombre de subdivisión (FR):',
		'static_currencies_item.cu_sub_name_es' => 'Nombre de subdivisión (ES):',
		'static_currencies_item.cu_symbol_left' => 'Símbolo a la izquierda:',
		'static_currencies_item.cu_symbol_right' => 'Símbolo a la derecha:',
		'static_currencies_item.cu_thousands_point' => 'Marca de los miles:',
		'static_currencies_item.cu_decimal_point' => 'Marca decimal:',
		'static_currencies_item.cu_decimal_digits' => 'Número de decimales:',
		'static_currencies_item.cu_sub_divisor' => 'Divisor:',
		'static_currencies_item.cu_sub_symbol_left' => 'Símbolo a la izquierda - Subdivisión:',
		'static_currencies_item.cu_sub_symbol_right' => 'Símbolo a la derecha - Subdivisión:',
	),
	'nl' => Array (
	),
	'cz' => Array (
	),
	'pl' => Array (
		'static_countries_item.cn_iso_2' => 'Kod kraju ISO 2:',
		'static_countries_item.cn_iso_3' => 'Kod kraju ISO 3:',
		'static_countries_item.cn_iso_nr' => 'Kod kraju ISO nr:',
		'static_countries_item.cn_official_name_local' => 'Nazwa oficjalna (lokalna):',
		'static_countries_item.cn_official_name_en' => 'Nazwa oficjalna (EN):',
		'static_countries_item.cn_capital' => 'Stolica:',
		'static_countries_item.cn_tldomain' => 'Domena najwy¿szego poziomu:',
		'static_countries_item.cn_currency_iso_nr' => 'Kod waluty ISO nr:',
		'static_countries_item.cn_currency_iso_3' => 'Kod waluty ISO 3:',
		'static_countries_item.cn_phone' => 'Prefiks tel.:',
		'static_countries_item.cn_eu_member' => 'Cz³onek EU:',
		'static_countries_item.cn_address_format' => 'Format adresu:',
		'static_countries_item.cn_address_format_1' => 'kod pocztowy, miasto',
		'static_countries_item.cn_address_format_2' => 'miasto, kod pocztowy',
		'static_countries_item.cn_address_format_3' => 'miasto, region, kod pocztowy',
		'static_countries_item.cn_zone_flag' => 'Flaga strefy:',
		'static_countries_item.cn_short_local' => 'Krótka nazwa (lokalna):',
		'static_countries_item.cn_short_en' => 'Krótka nazwa (EN):',
		'static_countries_item.cn_short_dk' => 'Krótka nazwa (DK):',
		'static_countries_item.cn_short_de' => 'Krótka nazwa (DE):',
		'static_country_zones_item.zn_country_iso_nr' => 'Kod kraju ISO nr:',
		'static_country_zones_item.zn_country_iso_2' => 'Kod kraju ISO 2:',
		'static_country_zones_item.zn_country_iso_3' => 'Kod kraju ISO 3:',
		'static_country_zones_item.zn_code' => 'Kod strefy:',
		'static_languages_item.lg_iso_2' => 'Kod jêzyka ISO 2:',
		'static_languages_item.lg_name_en' => 'Nazwa (EN):',
		'static_languages_item.lg_name_fr' => 'Nazwa (FR):',
		'static_languages_item.lg_name_de' => 'Nazwa (DE):',
		'static_languages_item.lg_name_es' => 'Nazwa (ES):',
		'static_languages_item.lg_name_nl' => 'Nazwa (NL):',
		'static_currencies_item.cu_iso_3' => 'Kod waluty ISO 3:',
		'static_currencies_item.cu_iso_nr' => 'Kod waluty ISO nr:',
		'static_currencies_item.cu_name_en' => 'Nazwa (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Podnazwa (EN):',
		'static_currencies_item.cu_name_de' => 'Nazwa (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Podnazwa (DE):',
		'static_currencies_item.cu_symbol_left' => 'Symbol z lewej:',
		'static_currencies_item.cu_symbol_right' => 'Symbol z prawej:',
		'static_currencies_item.cu_thousands_point' => 'Separator tysiêcy:',
		'static_currencies_item.cu_decimal_point' => 'Separator czê¶ci dziesiêtnych:',
		'static_currencies_item.cu_decimal_digits' => 'Liczba cyfr dziesiêtnych:',
		'static_currencies_item.cu_sub_divisor' => 'Separator:',
		'static_currencies_item.cu_sub_symbol_left' => 'Podsymbol z lewej:',
		'static_currencies_item.cu_sub_symbol_right' => 'Podsymbol z prawej:',
	),
	'si' => Array (
	),
	'fi' => Array (
		'static_countries.title' => 'Pysyvät maatiedot',
		'static_countries_item.cn_iso_2' => 'ISO 2 maakoodi:',
		'static_countries_item.cn_iso_3' => 'ISO 3 maakoodi:',
		'static_countries_item.cn_iso_nr' => 'ISO nr maakoodi:',
		'static_countries_item.cn_official_name_local' => 'Virallinen nimi (paikallinen):',
		'static_countries_item.cn_official_name_en' => 'Virallinen nimi (EN):',
		'static_countries_item.cn_capital' => 'Pääkaupunki:',
		'static_countries_item.cn_tldomain' => 'Päätason domain:',
		'static_countries_item.cn_currency_iso_nr' => 'ISO nr valuuttakoodi:',
		'static_countries_item.cn_currency_iso_3' => 'ISO 3 valuuttakoodi:',
		'static_countries_item.cn_phone' => 'Kans.väl. puhelin nro:',
		'static_countries_item.cn_eu_member' => 'Eu jäsen:',
		'static_countries_item.cn_address_format' => 'Osoitteen malli:',
		'static_countries_item.cn_address_format_1' => 'postinumero, kaupunki',
		'static_countries_item.cn_address_format_2' => 'kaupunki postinumero',
		'static_countries_item.cn_address_format_3' => 'kaupunki alue postinumero',
		'static_countries_item.cn_address_format_4' => 'kaupunki (aluenimi) postinumero',
		'static_countries_item.cn_address_format_5' => 'kaupunki / postinumero',
		'static_countries_item.cn_address_format_6' => 'kaupunki, aluekoodi',
		'static_countries_item.cn_address_format_7' => 'kaupunki aluekoodi',
		'static_countries_item.cn_address_format_8' => 'kaupunki (aluenimi)',
		'static_countries_item.cn_zone_flag' => 'Vyöhyke lippu:',
		'static_countries_item.cn_short_local' => 'Lyhyt nimi (paikallinen):',
		'static_countries_item.cn_short_en' => 'Lyhyt nimi (EN):',
		'static_countries_item.cn_short_dk' => 'Lyhyt nimi (DK):',
		'static_countries_item.cn_short_de' => 'Lyhyt nimi (DE):',
		'static_country_zones.title' => 'Pysyvät maatietojen alajaot',
		'static_country_zones_item.zn_country_iso_nr' => 'ISO nr maakoodi:',
		'static_country_zones_item.zn_country_iso_2' => 'ISO 2 maakoodi:',
		'static_country_zones_item.zn_country_iso_3' => 'ISO 3 maakoodi:',
		'static_country_zones_item.zn_code' => 'Vyöhykekoodi:',
		'static_country_zones_item.zn_name_local' => 'Paikallinen nimi',
		'static_languages.title' => 'Kielet',
		'static_languages_item.lg_iso_2' => 'ISO 2 maakoodi:',
		'static_languages_item.lg_name_en' => 'Nimi (EN):',
		'static_languages_item.lg_typo3' => 'Typo3 kieli koodi:',
		'static_currencies.title' => 'Pysyvät valuuttakoodit',
		'static_currencies_item.cu_iso_3' => 'ISO 3 valuuttakoodi:',
		'static_currencies_item.cu_iso_nr' => 'ISO nr valuuttakoodi:',
		'static_currencies_item.cu_name_en' => 'Nimi (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Alanimi (EN):',
		'static_currencies_item.cu_name_de' => 'Nimi (DE):',
		'static_currencies_item.cu_name_fr' => 'Nimi (FR)',
		'static_currencies_item.cu_name_es' => 'Nimi (ES)',
		'static_currencies_item.cu_sub_name_de' => 'Alanimi (DE):',
		'static_currencies_item.cu_sub_name_fr' => 'Alanimi (FR)',
		'static_currencies_item.cu_sub_name_es' => 'Alanimi (ES)',
		'static_currencies_item.cu_symbol_left' => 'Symboli vasen:',
		'static_currencies_item.cu_symbol_right' => 'Symboli oikea:',
		'static_currencies_item.cu_thousands_point' => 'Tuhaterotin:',
		'static_currencies_item.cu_decimal_point' => 'Desimaalierotin:',
		'static_currencies_item.cu_decimal_digits' => 'Desimaalien määrä:',
		'static_currencies_item.cu_sub_divisor' => 'Jakaja:',
		'static_currencies_item.cu_sub_symbol_left' => 'Alasymboli vasen:',
		'static_currencies_item.cu_sub_symbol_right' => 'Alasymboli oikea:',
	),
	'tr' => Array (
	),
	'se' => Array (
	),
	'pt' => Array (
	),
	'ru' => Array (
	),
	'ro' => Array (
		'static_countries_item.cn_iso_2' => 'Codul ISO 2 al tarii:',
		'static_countries_item.cn_iso_3' => 'Codul ISO 3 al tarii:',
		'static_countries_item.cn_iso_nr' => 'Codul ISO al tarii:',
		'static_countries_item.cn_official_name_local' => 'Numele oficial (local):',
		'static_countries_item.cn_official_name_en' => 'Numele oficial (EN):',
		'static_countries_item.cn_capital' => 'Capitala:',
		'static_countries_item.cn_tldomain' => 'Domeniu de varf:',
		'static_countries_item.cn_currency_iso_nr' => 'Numarul ISO al valutei:',
		'static_countries_item.cn_currency_iso_3' => 'Codul ISO 3 al valutei:',
		'static_countries_item.cn_phone' => 'Prefix telefon intern:',
		'static_countries_item.cn_eu_member' => 'Membru EU:',
		'static_countries_item.cn_address_format' => 'Format adresa:',
		'static_countries_item.cn_address_format_1' => 'zip oras',
		'static_countries_item.cn_address_format_2' => 'oras zip',
		'static_countries_item.cn_address_format_3' => 'oras regiune zip',
		'static_countries_item.cn_zone_flag' => 'Steagul zonei:',
		'static_countries_item.cn_short_local' => 'Nume prescurtat (local):',
		'static_countries_item.cn_short_en' => 'Nume prescurtat (EN):',
		'static_countries_item.cn_short_dk' => 'Nume prescurtat (DK):',
		'static_countries_item.cn_short_de' => 'Nume prescurtat (DE):',
		'static_country_zones_item.zn_country_iso_nr' => 'Codul ISO al tarii:',
		'static_country_zones_item.zn_country_iso_2' => 'Codul ISO 2 al tarii:',
		'static_country_zones_item.zn_country_iso_3' => 'Codul ISO 3 al tarii:',
		'static_country_zones_item.zn_code' => 'Codul zonei:',
		'static_languages_item.lg_iso_2' => 'Codul ISO 2 al limbii:',
		'static_languages_item.lg_name_en' => 'Nume (EN):',
		'static_currencies_item.cu_iso_3' => 'Codul ISO 3 al valutei:',
		'static_currencies_item.cu_iso_nr' => 'Numarul ISO al valutei:',
		'static_currencies_item.cu_name_en' => 'Nume (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Subnume (EN):',
		'static_currencies_item.cu_name_de' => 'Nume (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Subnume (DE):',
		'static_currencies_item.cu_symbol_left' => 'Simbol stanga:',
		'static_currencies_item.cu_symbol_right' => 'Simbol dreapta:',
		'static_currencies_item.cu_thousands_point' => 'Punct mii:',
		'static_currencies_item.cu_decimal_point' => 'Punct zecimal:',
		'static_currencies_item.cu_decimal_digits' => 'Caractere decimale:',
		'static_currencies_item.cu_sub_divisor' => 'Diviziune:',
		'static_currencies_item.cu_sub_symbol_left' => 'Subsimbol dreapta:',
		'static_currencies_item.cu_sub_symbol_right' => 'Subsimbol stanga:',
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
	'is' => Array (
	),
	'hr' => Array (
	),
	'hu' => Array (
	),
	'gl' => Array (
	),
	'th' => Array (
	),
	'gr' => Array (
	),
	'hk' => Array (
	),
	'eu' => Array (
	),
	'bg' => Array (
	),
	'br' => Array (
		'static_countries_item.cn_iso_2' => 'Código ISO 2 do país:',
		'static_countries_item.cn_iso_3' => 'Código ISO 3 do país:',
		'static_countries_item.cn_iso_nr' => 'Código ISO nr do país:',
		'static_countries_item.cn_official_name_local' => 'Nome oficial (local):',
		'static_countries_item.cn_official_name_en' => 'Nome oficial (EN):',
		'static_countries_item.cn_capital' => 'Capital',
		'static_countries_item.cn_tldomain' => 'Domínio nível 1:',
		'static_countries_item.cn_currency_iso_nr' => 'Código ISO nr da moeda:',
		'static_countries_item.cn_currency_iso_3' => 'Código ISO 3 da moeda:',
		'static_countries_item.cn_phone' => 'Prefixo internacional de telefone:',
		'static_countries_item.cn_eu_member' => 'Membro da UE:',
		'static_countries_item.cn_address_format' => 'Formato de endereço:',
		'static_countries_item.cn_address_format_1' => 'cep, cidade',
		'static_countries_item.cn_address_format_2' => 'cidade, cep',
		'static_countries_item.cn_address_format_3' => 'cidade, região, cep',
		'static_countries_item.cn_zone_flag' => 'Zona:',
		'static_countries_item.cn_short_local' => 'Nome curto (local):',
		'static_countries_item.cn_short_en' => 'Nome curto (EN):',
		'static_countries_item.cn_short_dk' => 'Nome curto (DK):',
		'static_countries_item.cn_short_de' => 'Nome curto (DE):',
		'static_country_zones_item.zn_country_iso_nr' => 'Código ISO nr do país:',
		'static_country_zones_item.zn_country_iso_2' => 'Código ISO 2 do país:',
		'static_country_zones_item.zn_country_iso_3' => 'Código ISO 3 do país:',
		'static_country_zones_item.zn_code' => 'Código da zona:',
		'static_languages_item.lg_iso_2' => 'Código ISO 2 do idioma:',
		'static_languages_item.lg_name_en' => 'Nome (EN):',
		'static_currencies_item.cu_iso_3' => 'Código ISO 3 da moeda:',
		'static_currencies_item.cu_iso_nr' => 'Código ISO nr da moeda:',
		'static_currencies_item.cu_name_en' => 'Nome (EN):',
		'static_currencies_item.cu_sub_name_en' => 'Sub nome (EN):',
		'static_currencies_item.cu_name_de' => 'Nome (DE):',
		'static_currencies_item.cu_sub_name_de' => 'Sub nome (DE):',
		'static_currencies_item.cu_symbol_left' => 'Símbolo esquerda:',
		'static_currencies_item.cu_symbol_right' => 'Símbolo direita:',
		'static_currencies_item.cu_thousands_point' => 'Pontuação de milhar:',
		'static_currencies_item.cu_decimal_point' => 'Pontuação decimal:',
		'static_currencies_item.cu_decimal_digits' => 'Dígitos decimais:',
		'static_currencies_item.cu_sub_divisor' => 'Divisor:',
		'static_currencies_item.cu_sub_symbol_left' => 'Sub-símbolo esquerda:',
		'static_currencies_item.cu_sub_symbol_right' => 'Sub-símbolo direita:',
	),
	'et' => Array (
	),
	'ar' => Array (
	),
	'he' => Array (
	),
	'ua' => Array (
	),
	'lv' => Array (
	),
	'jp' => Array (
	),
	'vn' => Array (
	),
	'ca' => Array (
	),
	'ba' => Array (
	),
	'kr' => Array (
	),
);
?>